#!/usr/bin/env php
<?php

require_once '../_config.php';


$restClient = new \Sirprize\Rest\Client($config);

$s3 = new \Sirprize\Amazon\S3($config);
$s3->setRestClient($restClient);

$bucket = $s3->getBucketsInstance()->getBucketInstance();
$bucket->setName(S3_BUCKET);

$newObjekt = $s3->getObjektsInstance()->getObjektInstance();
$newObjekt
	->setBucket($bucket)
	->setKey('4O88nAT5eaRP.gif')
;

$objekt = $s3->getObjektsInstance()->getObjektInstance();

$objekt
	->addEventsToListener($s3->getEventPrinterInstance())
	->addEventsToListener($s3->getEventLoggerInstance()->setLog($log))
	->setBucket($bucket)
	->setKey(S3_OBJECT)
	->copy($newObjekt, null, 2)
;

if($objekt->getResponseHandler()->isError())
{
	print 'Code: '.$objekt->getResponseHandler()->getCode()."\n";
	print 'Message: '.$objekt->getResponseHandler()->getMessage()."\n";
	exit;
}