#!/usr/bin/env php
<?php

require_once '../_config.php';


$restClient = new \Sirprize\Rest\Client($config);

$service = new \Sirprize\Amazon\S3\Service($config);
$service->setRestClient($restClient);

$bucket = $service->getBucketsInstance()->getBucketInstance();
$bucket->setName(S3_BUCKET);

$newObjekt = $service->getObjektsInstance()->getObjektInstance();
$newObjekt
	->setBucket($bucket)
	->setKey('20110821-vision-new.jpg')
;

$objekt = $service->getObjektsInstance()->getObjektInstance();

$objekt
	->addEventsToListener($service->getEventPrinterInstance())
	->addEventsToListener($service->getEventLoggerInstance()->setLog(getLog('test')))
	->setBucket($bucket)
	->setKey(S3_OBJECT)
	->copy($newObjekt, null, 2)
;

if($objekt->getResponseHandler()->isError())
{
	print 'Code: '.$objekt->getResponseHandler()->getCode()."\n";
	print 'Message: '.$objekt->getResponseHandler()->getMessage()."\n";
	exit;
}