#!/usr/bin/env php
<?php

require_once '../_config.php';


$restClient = new \Sirprize\Rest\Client($config);

$service = new \Sirprize\Amazon\S3\Service($config);
$service->setRestClient($restClient);

$bucket = $service->getBucketsInstance()->getBucketInstance();
$bucket->setName(S3_BUCKET);

$prefix = 'bmx';
$delimiter = '';
$maxKeys = 1000;

$objekts = null;
$lastKey = null; // last object-key is used as marker for next request
$count = 0;

while($objekts === null || $objekts->getIsTruncated())
{
	$objekts = $service->getObjektsInstance();
	$objekts
		->setPrefix($prefix)
		->setDelimiter($delimiter)
		->setMarker($lastKey)
		->setMaxKeys($maxKeys)
		->startAllInBucket($bucket)
	;
	
	foreach($objekts as $objekt)
	{
		print $bucket->getName().'/'.$objekt->getKey()."\n";
		$lastKey = $objekt->getKey();
		$count++;
	}
	
	print "-------------------------\n";
}

print "number of object: $count\n";