#!/usr/bin/env php
<?php

require_once '../_config.php';


$restClient = new \Sirprize\Rest\Client($config);

$s3 = new \Sirprize\Amazon\S3($config);
$s3->setRestClient($restClient);

$bucket = $s3->getBucketsInstance()->getBucketInstance();
$bucket->setName(S3_BUCKET);

$prefix = 'Assets/Tracks/PreVi';
$delimiter = '';
$maxKeys = 1000;

$objekts = null;
$lastKey = null; // last object-key is used as marker for next request

while($objekts === null || $objekts->getIsTruncated())
{
	$objekts = $s3->getObjektsInstance();
	$objekts
		->setPrefix($prefix)
		->setDelimiter($delimiter)
		->setMarker($lastKey)
		->setMaxKeys($maxKeys)
		->startAllInBucket($bucket)
	;
	
	foreach($objekts as $objekt)
	{
		$objekt
			->setEventManager($s3->getEventManagerInstance())
			->addEventsToListener($s3->getEventPrinterInstance())
			->addEventsToListener($s3->getEventLoggerInstance()->setLog($log))
			->delete(2)
		;
		#print $bucket->getName().'/'.$objekt->getKey()."\n";
		$lastKey = $objekt->getKey();
	}
}