#!/usr/bin/env php
<?php

require_once '../_config.php';


$restClient = new \Sirprize\Rest\Client($config);
#$restClient->setCache($cache);

$service = new \Sirprize\Amazon\S3\Service($config);
$service->setRestClient($restClient);

$bucket = $service->getBucketsInstance()->getBucketInstance();
$bucket->setName(S3_BUCKET);

$objekts = $service->getObjektsInstance();

$objekts
	->addEventsToListener($service->getEventPrinterInstance())
	->addEventsToListener($service->getEventLoggerInstance()->setLog(getLog('test')))
	->setPrefix('bmx')
	#->setDelimiter('jpg')
	->setMaxKeys(10)
	->startAllInBucket($bucket, 2)
;

if($objekts->getResponseHandler()->isError())
{
	print 'Code: '.$objekts->getResponseHandler()->getCode()."\n";
	print 'Message: '.$objekts->getResponseHandler()->getMessage()."\n";
	exit;
}

print 'Prefix: '.$objekts->getPrefix()."\n";
print 'Marker: '.$objekts->getMarker()."\n";
print 'MaxKeys: '.$objekts->getMaxKeys()."\n";
print 'Delimiter: '.$objekts->getDelimiter()."\n";
print 'IsTruncated: '.$objekts->getIsTruncated()."\n";
print "--------------------------------------\n";

$count = 1;

foreach($objekts as $objekt)
{
	print $count++.' - '.$objekt->getKey().' - '.$objekt->getSize().' - '.$objekt->getOwner()->getDisplayName()."\n";
}