#!/usr/bin/env php
<?php

require_once '../_config.php';


use \Sirprize\Amazon\S3;


$restClient = new \Sirprize\Rest\Client($config);

$service = new S3($config);
$service->setRestClient($restClient);

$bucket = $service->getBucketsInstance()->getBucketInstance();
$bucket->setName(S3_BUCKET);

$headers = $service->getHeadersInstance();
#$headers->add(S3\Headers::CANNED_ACL_NAME.':'.S3\Headers::ACL_PUBLIC_READ);

$mirror = new S3\Tools\Mirror();
$mirror
	->setService($service)
	->setEventManager($service->getEventManagerInstance())
	->addEventsToListener($service->getEventPrinterInstance())
	->addEventsToListener($service->getEventLoggerInstance()->setLog(getLog('test')))
	#->force(true)
	#->printMessages(true)
	->setTargetRenamePattern('/^bmx\/IMG_(.*)/', 'bmx2/$1')
	#->addExcludePattern('/^(01|_Backups|_Logs|_Test)/')
	->run($bucket, $bucket, 'bmx/IMG', '', $headers)
;